### ISSUE TITLE
Not realy an issue, Just a recomendation

### ISSUE THREAD

**Issue by Typhlosion-afk** [randomusernamea/BiomeOdds#1]
Hi Dev team, i am a player with full starter dex and now i try to hunt my favourite shiny pokemons. I finished 5850 rounds in endless about 10-12 times (both splicer).
I’ve come to realize that searching for some of them is really difficult, and I understand that the game needs some challenges to keep players interested, which I agree with. However, when I’m only missing a single Miraidon and after completing Endless five times, I still haven’t encountered any Ultra rate Bosses in the Laboratory, it’s truly a terrible experience. The chances of getting to certain areas are too low, not to mention arriving at that area on floor 2998 and it ends after encountering two Electrodes. >.< My heart gets Self-Destruct… 2 times >.< I really wish there was something to alleviate this frustration, something like a Map item, for instance. You could add some conditions for it to appear in the Shop (like needing to pass through all areas at least once, or the item only appears after round 2000 or something similar). Just having something that helps players improve efficiency and the chances of entering rare areas… that would be really helpful…
One more time thank you verry much for your game, it's really nice.
![pkm](https://github.com/randomusernamea/BiomeOdds/assets/53886636/e4a817f3-07e9-487b-8759-b2486d63dd7e)

**Comment by randomusernamea** [comment]
I am not a pokerogue dev.
